# Stolen from https://github.com/LiliC/travis-minikube/tree/minikube-30-kube-1.12
# Using travis only because CircleCI does not support systemd and hence minikube
sudo: required

language: python
python:
- "3.6"

# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial

install:
  - ./.ci/setup-minikube.bash
  - kubectl cluster-info

script:
- true